name: diainfo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^29.1.41
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/signup-background.png
    - assets/avatar.png