// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwM5XfeheK2GtoIO7tPuumouBB2fZIo0k',
    appId: '1:770573242070:web:9afcd2efe877f488520377',
    messagingSenderId: '770573242070',
    projectId: 'diainfo-1e967',
    authDomain: 'diainfo-1e967.firebaseapp.com',
    storageBucket: 'diainfo-1e967.firebasestorage.app',
    measurementId: 'G-CQ6GCDJ6LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiAtHDRSltw1ze199kd3ESmXtHZQ0RS_U',
    appId: '1:770573242070:android:169cc228a1903d52520377',
    messagingSenderId: '770573242070',
    projectId: 'diainfo-1e967',
    storageBucket: 'diainfo-1e967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSMpaz5OqtB6Wr-Hg43zWKIobFySbwS2c',
    appId: '1:770573242070:ios:9b28025ff17b56ee520377',
    messagingSenderId: '770573242070',
    projectId: 'diainfo-1e967',
    storageBucket: 'diainfo-1e967.firebasestorage.app',
    iosBundleId: 'com.example.diainfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSMpaz5OqtB6Wr-Hg43zWKIobFySbwS2c',
    appId: '1:770573242070:ios:9b28025ff17b56ee520377',
    messagingSenderId: '770573242070',
    projectId: 'diainfo-1e967',
    storageBucket: 'diainfo-1e967.firebasestorage.app',
    iosBundleId: 'com.example.diainfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwM5XfeheK2GtoIO7tPuumouBB2fZIo0k',
    appId: '1:770573242070:web:b51448db98044bf6520377',
    messagingSenderId: '770573242070',
    projectId: 'diainfo-1e967',
    authDomain: 'diainfo-1e967.firebaseapp.com',
    storageBucket: 'diainfo-1e967.firebasestorage.app',
    measurementId: 'G-VLJB2235SN',
  );
}
